name: C/C++ CI

on: [push]

jobs:
  compile_check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.2
      with:
        submodule_update: OFF
        run_tests: OFF
        unit_test_build: -Dtest=ON
  mail: 
      runs-on: ubuntu-latest
      #needs: compile_check
      steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - run: sudo apt-get install sendmail mutt
      - run: tar -czvf code.tar.gz project2/code
      - run: echo "не забыть представиться" | mutt -a "code.tar.gz" -s "код" -- gri279@gmail.com
